# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-23 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=16, verbose_name='管理员姓名')),
                ('admin_passwd', models.CharField(max_length=128, verbose_name='管理员密码')),
                ('admin_gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别')),
                ('admin_email', models.EmailField(max_length=254, verbose_name='管理员邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False, verbose_name='图书编号')),
                ('book_name', models.CharField(max_length=128, verbose_name='图书名称')),
                ('book_author', models.CharField(max_length=128, verbose_name='图书作者')),
                ('book_press', models.CharField(max_length=128, verbose_name='图书出版社')),
                ('book_num', models.IntegerField(verbose_name='图书数量')),
                ('book_sort', models.CharField(max_length=128, verbose_name='图书类别')),
                ('book_recore', models.DateField(verbose_name='图书入库时间')),
                ('book_publish_date', models.DateField(verbose_name='图书出版时间')),
            ],
        ),
        migrations.CreateModel(
            name='BookBorrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(verbose_name='借书时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='图书')),
            ],
        ),
        migrations.CreateModel(
            name='Bookreturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(verbose_name='归还时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='图书')),
            ],
        ),
        migrations.CreateModel(
            name='BookSort',
            fields=[
                ('book_sort_id', models.AutoField(primary_key=True, serialize=False, verbose_name='图书类别编号')),
                ('book_sort_name', models.CharField(max_length=128, verbose_name='图书类别名称')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户编号')),
                ('user_name', models.CharField(max_length=128, verbose_name='用户姓名')),
                ('user_passwd', models.CharField(max_length=128, verbose_name='用户密码')),
                ('user_gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=32, verbose_name='性别')),
                ('user_email', models.EmailField(max_length=254, unique=True, verbose_name='用户邮箱')),
            ],
        ),
        migrations.AddField(
            model_name='bookreturn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='bookborrow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.User', verbose_name='用户'),
        ),
    ]
