# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-23 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20180623_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreturn',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookreturn',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookSort',
        ),
        migrations.AlterField(
            model_name='bookborrow',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
        ),
        migrations.AlterField(
            model_name='bookborrow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.User'),
        ),
        migrations.DeleteModel(
            name='Bookreturn',
        ),
    ]
