# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-23 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20180623_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='permission',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.IntegerField(default=0),
        ),
    ]
