# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-24 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20180623_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='admin_gender',
            new_name='admingender',
        ),
        migrations.RenameField(
            model_name='administrator',
            old_name='admin_id',
            new_name='adminid',
        ),
        migrations.RenameField(
            model_name='administrator',
            old_name='admin_name',
            new_name='adminname',
        ),
        migrations.RenameField(
            model_name='administrator',
            old_name='admin_passwd',
            new_name='adminpasswd',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_author',
            new_name='bookauthor',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_id',
            new_name='bookid',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_name',
            new_name='bookname',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_num',
            new_name='booknum',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_press',
            new_name='bookpress',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_publish_date',
            new_name='bookpublish_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_recore',
            new_name='bookrecore',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_sort',
            new_name='booksort',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_gender',
            new_name='usergender',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_passwd',
            new_name='userpasswd',
        ),
    ]
